name: WorldShaper
version: 0.1_SNAPSHOT
author: CodedStingray
main: net.codedstingray.worldshaper.WorldShaper
api-version: 1.19
description: WorldShaper is an in-game map editor.
commands:
  wand:
    description: Gives you the WorldShaper selection wand.
    usage: /<command>
