name: WorldShaper
version: 0.1-SNAPSHOT
author: CodedStingray
main: net.codedstingray.worldshaper.WorldShaper
api-version: 1.20
description: WorldShaper is an in-game map editor.
commands:
  worldshaper:
    description: Sends WorldShaper information to the caller.
    usage: /<command>
  wand:
    description: Gives you the WorldShaper selection wand.
    usage: /<command>
  undo:
    description: Undoes the last action.
    usage: /<command>
  redo:
    description: Redoes the last undone action.
    usage: /<command>
  pos:
    description: Adds your current position as a control position for your selection.
    usage: /<command> [index]
  positions:
    description: Lists all current control positions for your selection.
    usage: /<command>
  removepos:
    description: Removes a control position
    usage: /<command> [index]
  clearpositions:
    description: Clears the list of selection control points.
    usage: /<command>
  selectiontype:
    description: Sets your selection type.
    usage: /<command> [selection type name]
  areatype:
    description: Sets your area type.
    usage: /<command> [area type name]
  movearea:
    description: Moves the area.
    usage: /<command> <distance> [direction]
  expand:
    description: Expands the area.
    usage: /<command> <amount> [direction]
  retract:
    description: Retracts the area.
    usage: /<command> <amount> [direction]
  set:
    description: Sets all blocks in the area to the provided Material pattern
    usage: /<command> <pattern>
  replace:
    description: Replaces all blocks of a given type with the new material
    usage: /<command> <mask> <pattern>
